# Generated by Django 2.0.6 on 2018-06-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mensajes',
            new_name='sugerencias',
        ),
    ]
